# Generated by Django 4.0.3 on 2022-04-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_author_quote_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('moderated', 'модерированная')], default='новая', max_length=50),
        ),
    ]
