# Generated by Django 4.0.3 on 2022-04-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('moderated', 'модерированная')], default='new', max_length=50),
        ),
    ]
